language: java
sudo: false
jdk:
  - oraclejdk8
  
before_script:
 - psql -c 'create database demo;' -U postgres
#install: ./gradlew check
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: 
    master: tmpchatbot